### ISSUE TITLE
Usuario puede abandonar un grupo al que pertenece.

### ISSUE THREAD

**Issue by danflop** [LBAB-Humboldt/BioModelos.v2#107]
Como usuario de BioModelos quisiera tener la opción de abandonar el grupo en el que esté.

**Comment by danflop** [comment]
Criterio de aceptación: La opción (botón) para salir de un grupo está habilitado y funcional.

**Comment by valegrajales** [comment]
Corregir el texto que sale en el cuadro de diálogo al retirarse del grupo.
