### ISSUE TITLE
Eliminar registros duplicados de la base de datos

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#11]
Es importante eliminar duplicados espejo de la base de datos.

**Comment by rickreyjim1** [comment]
The development db (192.168.11.81:27017 prueba) was updated:
Unsetting some fields:
db.records.updateMany({},{"$unset": {"cites": "", "consecutivoID":"", "endemic": "", "hasTaxDoubt":"", "invasive":"", "otherID": "", "privateDataset": "", "recSizeBytes":"", "scriptID": "", "tmpGeo": "", "tmpTax": "", "withLat": "", "withLon":""}})
db.species.updateMany({},{"$unset": {"consecutivoID": "", "originalGenus": "", "originalScientificNameID": "", "originalSpecificEpithet": "", "scientificNameID": ""}})
db.models.updateMany({},{"$unset": {"tifPath": "", "sttCoverLC1": ""}})
Setting new fields:
db.records.updateMany({},{"$set": {"interpretedElevation": null}})
db.species.updateMany({},{"$set": {"migratoryType": null}})
db.models.updateMany({},{"$set": {"published": false, "customCitation": null}})
Identifying the duplicated records (in prueba.records collection):
db.records.aggregate([{ $group: { _id: { "occurrenceID": "$occurrenceID" },  uniqueIds: { $addToSet: "$_id" },  count: { $sum: 1 }}}, { $match: { count: { $gt: 1 }}}, {"$project": {_id: 0, "Duplicado": "$_id.occurrenceID", "Cantidad": "$count"}},  {"$out": "duplicadosRecords"}])
The previous query count is 8433.

Removing the duplicates:
db.records.aggregate([{ "$group": {"_id": { "occurrenceID": "$occurrenceID" }, "dups": { "$push": "$_id" },
        "count": { "$sum": 1 }}}, { "$match": { "count": { "$gt": 1 } }}]).forEach(function(doc) {doc.dups.shift();
    db.records.remove({ "_id": {"$in": doc.dups }});});
