### ISSUE TITLE
Crear sección "VER MAS" con información completa de un registro

### ISSUE THREAD

**Issue by rbastidas** [LBAB-Humboldt/BioModelos.v2#112]
Consumir servicio que muestre toda la información de un registro en una plantilla simple sin el histórico.

1. Diseño de nueva caja de registro.
2. Implementación de llamada a servicios de registros.
3. Funcionalidad de edición.

**Comment by rbastidas** [comment]
Criterio de aceptación: Sección "VER MAS" con información detallada de un registro.

**Comment by erikasv** [comment]
El punto 1 se realizó.
El punto 2 se realizó, pero hay nuevos cambios en el diccionario de datos que hay que validar en tareas futuras.
El punto 3 se implementará en el futuro (nueva tarea)
