### ISSUE TITLE
Ajustar cambios de la base de datos en el código de Biomodelos

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#12]
Se debe revisar campo por campo, qué cambios hubo de modo que se reflejen en el código de la aplicación.

**Comment by rickreyjim1** [comment]
After DB update (issue #11), the code was updated too:
mongoose.connect("mongodb://localhost:27017/prueba")//development DB
var port = process.env.PORT || 4000;//not interferring with 3000.

**Comment by danflop** [comment]
Se ajustaron los cambios principales que afectan las funcionalidades de carga de especies, registros y modelos. Queda pendiente el ajuste de la funcionalidad de búsqueda ya que requiere un desarrollo adicional en el servicio web.
