### ISSUE TITLE
La página no carga de forma responsiva

### ISSUE THREAD

**Issue by rickreyjim1** [LBAB-Humboldt/BioModelos.v2#14]
La página no carga de forma responsiva cuando se prueba en diferentes tamaños de pantalla de dispositivos móviles utilizando las herramientas de desarrollador de Google Chrome. Sin embargo, funciona correctamente al cambiar el tamaño de la pantalla manualmente.

**Comment by danflop** [comment]
Se agregó la siguiente línea al head de la aplicación para solucionarlo:
`<meta name="viewport" content="width=device-width; initial-scale=1.0">`
