### ISSUE TITLE
Revisión y ajuste de colecciones Records y Models.

### ISSUE THREAD

**Issue by danflop** [LBAB-Humboldt/BioModelos.v2#143]
Revisión y ajuste de colecciones Records y Models de acuerdo a los cambios en la colección Species.

**Comment by uamoreno** [comment]
Esta tarea correspondía a la tarea de revisión de las colecciones species y records respecto a los problemasd de duplicidad presentados desde octubre de 2018. 
Sería una tarea duplicada.

**Comment by uamoreno** [comment]
Se realizó el ajuste de la información en la base de datos de producción y se tomó backup.
