### ISSUE TITLE
Estudio de base de datos MongoDB

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#2]
Como desarrollador de BioModelos quiero conocer el estado actual de la base de datos mongo de Biomodelos para contribuir a futuros desarrollos

**Comment by valegrajales** [comment]
Criterios de aceptación: Presentación base de datos BioModelos. Requerimientos funcionalidades de carga información a base de datos definidos. Requerimientos consultas desde BioModelos definidos. Campos de base de datos definidos y descritos. Determinar campos editables de registros.

**Comment by rickreyjim1** [comment]
Please, take a look for: 
https://docs.google.com/document/d/1fDWaLuA5yVaIkCQKHrdpVwWSzhk7peNVoM8PwCYT8ts/edit

**Comment by valegrajales** [comment]
Criterios de aceptación 2: Subir script de validación de modelo de  mongodb al repositorio. Revisar con valentina el script de validación. Probar con datos reales el proceso de validación.

**Comment by rickreyjim1** [comment]
The wiki was made. Created the data examples. Inserted the missed field in records.models collection, modelDataValidationModel.js and updatingModels.js.  Updated the webservice REC 1 with the environmentalOutlier as a response field.
