### ISSUE TITLE
Cargar una de las hipótesis disponibles con mejor calificación en el visor cuando se seleccione una especie

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#20]
Como usuario de BioModelos quiero que al consultar y seleccionar una especie, se muestre automáticamente en el visor una de las hipótesis disponibles con mayor valor cuando no exista un modelo validado.

**Comment by valegrajales** [comment]
Criterios de aceptación: Cuando se busca una especie que tiene mas de una hipótesis que están empatadas o no evaluadas, se toma la primera y aparece un pop up diciendo que esa es una de varias hipótesis con la misma calificación que pueden ser consultadas en la sección hipótesis disponibles.

**Comment by danflop** [comment]
Junto con @jivelasquezt se acordó fusionar este Issue con el #19. De esta manera se cargará siempre la hipótesis con mejor calificación (O la primera con mejor calificación en caso de existir empates) y se mostrará el mismo mensaje en el pop-up.
