### ISSUE TITLE
Volver a revisar: Mostrar más tiempo el mensaje exitoso al enviar modelo

### ISSUE THREAD

**Issue by erikasv** [LBAB-Humboldt/BioModelos.v2#218]
La situación original es esta:

Cuando se envía un modelo (en la sección crear o editar modelo) aparece un mensaje de confirmación, al aceptarlo debe aparecer otro mensaje indicando que el modelo se envió exitosamente, este último mensaje no se alcanza a leer.

Lo que se va a hacer ahora es volver a revisar el código para verificar cómo es la funcionalidad y cómo debería ser para verificar el comentario del 4 de junio.

**Comment by erikasv** [comment]
Adicional a este inconveniente se encontró que la funcionalidad debería ser diferente, procedemos a mover la tarea de sprint y proseguir con la migración sin este ajuste

**Comment by erikasv** [comment]
Solucionar también los problemas que se encontraron al revisar la versión 5.1 (pero que no son exclusivos de esta versión) con las alertas que dejan un div sobre toda la página al cerrar los modales

**Comment by erikasv** [comment]
Para el comentario del 8 de julio: El problema del div transparente sobre toda la página se resolvió al migrar Rails a la versión 6 pues se cambió la librería alertify por una gema de la misma.

**Comment by cazapatamar** [comment]
Generar unos polígonos en la edición del modelo y revisar: (1) Clic en enviar (2) Clic en pausar y enviar

**Comment by erikasv** [comment]
Efectivamente la alerta se arregló con la actualización de alertify, la segunda alerta se muestra hasta que se le da "ok" y ya no queda ningún div bloqueando nada más. Faltaría ajustar los títulos de las alertas, pero para eso ya debe haber otra tarea.
