### ISSUE TITLE
Code review of SPE3

### ISSUE THREAD

**Issue by rickreyjim1** [LBAB-Humboldt/BioModelos.v2#23]
The SPE3 webService is a continuous concatenation of ifs. Maybe will be a better way to code all the bodyQuery + params?
How can be used the webService without parameters, just bodyQuery (endangered, endemic, invasive and migratory) to "filter" the species shown?

**Comment by danflop** [comment]
Issue moved to [LBAB-Humboldt/biomodelos_db_api #5](https://github.com/LBAB-Humboldt/biomodelos_db_api/issues/5) via [**ZenHub**](https://www.zenhub.com/)
