### ISSUE TITLE
Probar la versión 6

### ISSUE THREAD

**Issue by erikasv** [LBAB-Humboldt/BioModelos.v2#234]
- [x] Usuario no registrado - @cazapatamar 
- [x] Usuario registrado - @alegnaaived 
- [x] Usuario experto - @erikasv 
- [x] Usuario moderador - @danflop

**Comment by cazapatamar** [comment]
En la descripción puse un checklist para que vayan marcando cuando acaben sus pruebas y podamos cerrar esta tarea cuando estén todas las pruebas @alegnaaived @danflop @erikasv
