### ISSUE TITLE
Roll back to a previous version (updated and/or reported) record

### ISSUE THREAD

**Issue by rickreyjim1** [LBAB-Humboldt/BioModelos.v2#25]
A record can be "rolled back" to a former version, and the last values must be saved as another part of the array.

**Comment by danflop** [comment]
Issue moved to [LBAB-Humboldt/biomodelos_db_api #7](https://github.com/LBAB-Humboldt/biomodelos_db_api/issues/7) via [**ZenHub**](https://www.zenhub.com/)
