### ISSUE TITLE
Pruebas sobre la libreria del scroll

### ISSUE THREAD

**Issue by danflop** [LBAB-Humboldt/BioModelos.v2#255]

**Comment by cazapatamar** [comment]
Sprint 9

**Comment by erikasv** [comment]
El scroll sobre la caja de nuevo registro no se ha arreglado

**Comment by erikasv** [comment]
@danflop Ahora sí creo que se hizo algo en todos los casos donde se usaba niceScroll. En las secciones estáticas se pudo configurar niceScroll para que funcionara bien, en las dinámicas (como términos y condiciones, crear registro, filtros de registros, entre otros) se removió completamente y se configuró el scroll por defecto para funcionara
