### ISSUE TITLE
Edición de información de grupo

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#26]
Como moderador quiero poder editar la información del grupo para mantenerla actualizada

**Comment by valegrajales** [comment]
Criterio de aceptación: Campos del perfil de grupo editables solo por los moderadores del mismo.

**Comment by danflop** [comment]
Se agregaron las gemas CarrierWave y Minimagick para la carga de archivos y manipulación de imágenes. Adicionalmente, se instalaron los paquetes imagemagick y libmagickwand-dev para el correcto funcionamiento de Minimagick.
