### ISSUE TITLE
Mensaje de confirmación tras solicitud enviada

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#28]
Como experto quiero que cuando me registre en un grupo aparezca un mensaje de confirmación (pop-up o similar) de que mi solicitud ha sido enviada.

**Comment by valegrajales** [comment]
Criterio de aceptación: Debe aparecer un pop-up o similar cuando solicito ingreso a un grupo.

**Comment by danflop** [comment]
@jivelasquezt Funcionalidad completa. Hace falta revisar los textos de las diferentes alertas que se muestran.
