### ISSUE TITLE
Enviar email de confirmación tras registro en grupo

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#29]
Como experto quiero que cuando mi solicitud de membresía en un grupo sea aprobada, me llegue un correo electrónico para saber que estoy en el grupo.

**Comment by valegrajales** [comment]
Criterio de aceptación: El usuario recibe un email cuando he sido aceptado en un grupo.

**Comment by danflop** [comment]
@jivelasquezt @CAScgutierrez Queda pendiente revisar los textos y plantillas de los correos según las diferentes notificaciones.
