### ISSUE TITLE
Sugerir especie en grupo

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#30]
Como experto quiero poder sugerir una especie a ser incluida en el grupo para hacer aportes a su distribución.

**Comment by valegrajales** [comment]
Criterio de aceptación: Es posible escoger cualquier especie que este en la colección especies y que no este asignada a un grupo existente.

**Comment by danflop** [comment]
La lógica de sugerencia de especies queda de la siguiente manera de acuerdo a lo discutido con @jivelasquezt : 

1. Los usuarios pueden sugerir una especie si son miembros del grupo en el que están realizando la sugerencia.
2. Si una especie ya ha sido sugerida, hace parte de otro grupo, o está pendiente de aprobación en otro grupo, no permite que sea sugerida nuevamente e informa al usuario la razón.
3. Si un moderador no acepta una especie, esta especie queda libre para ser sugerida en otro grupo.
