### ISSUE TITLE
Enviar mensaje a integrantes de grupo

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#31]
Como moderador quiero poder enviar mensajes a todos los miembros del grupo para mantener el contacto.

**Comment by valegrajales** [comment]
Criterio de aceptación: La funcionalidad email debe estar implementada para moderadores en sus grupos.

**Comment by danflop** [comment]
La funcionalidad permite a los moderadores el envío de un mensaje desde el perfil de grupo, a todos los miembros del mismo.
