### ISSUE TITLE
Ver estadísticas derivadas de la distribución de especie

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#32]
Como usuario de biomodelos quiero ver estadísticas derivadas de la distribución de una especie para conocer estado y tendencias.

**Comment by valegrajales** [comment]
Criterio de aceptación: Los datos estadísticos del modelo son visibles en el frontend de Biomodelos

**Comment by danflop** [comment]
@jivelasquezt Se adicionan: cambio de tipo en el campo "modelID" (numérico a string)  en la base de datos SQL y su respectivo cambio en el código fuente, cambio de estructura de carpetas de archivos estáticos de modelos y adición de estas nuevas rutas al código de Rails.

**Comment by danflop** [comment]
Se realizaron los ajustes apropiados según los cambios en la base de datos de MongoDB. Los datos estadísticos son visibles en el frontend, sin embargo hay que realizar los siguientes ajustes en la base de datos:

1. Por el momento todos los modelos nivel 2 estarán inactivos.
2. Algunos datos con tildes tienen que ser cambiados a mano mientras se resuelve el issue de codificación.
3. Se debe eliminar el path de la ruta de todos los modelos (modelos, thumbnails y archivos .zip), dejando sólo el nombre del archivo con su extensión.
