### ISSUE TITLE
Mostrar icono para miembro aceptado en un grupo

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#39]
Mostrar icono para miembro aceptado en un grupo

**Comment by danflop** [comment]
Criterio de aceptación: Una vez un usuario de BioModelos sea aceptado en un grupo, aparecerá un icono de miembro actual del grupo en la misma ubicación en la que aparece el de miembro pendiente y el de pendiente de aprobación.
