### ISSUE TITLE
Mostrar estadísticas: especie que trabajo, avance tareas y mapas publicados en perfil

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#43]
Como usuario de biomodelos quiero que las estadisticas especies en que trabajo, avace en tareas y mapas publicados, aparezcan en mi perfil.

**Comment by valegrajales** [comment]
Criterio de aceptación: Las estadísticas mencionadas son calculadas dinámicamente (i.e. contra la base de datos) y si no tengo tareas, o mas o especies, el cuadro aparece vacío, es decir, no se muestra 0 (excepto en avance en tareas).

**Comment by danflop** [comment]
@jivelasquezt  @rbastidas @valegrajales Queda pendiente el ajuste de la estadística de mapas publicados. Para esta consulta se recomienda desarrollar un nuevo servicio web que retorne el número de modelos publicados por un usuario una vez se le pase como parámetro el ID del usuario en BioModelos.
