### ISSUE TITLE
Hacer que las estadísticas correspondan a datos reales para cada solicitud

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#48]
Bug: las estadísticas especies en agenda y modelos aprobados no son dinámicas (i.e. están quemadas)

**Comment by valegrajales** [comment]
Criterio de aceptación: Las estadísticas deben corresponder a los datos actuales almacenados en las bases de datos de Biomodelos.

**Comment by danflop** [comment]
@jivelasquezt Hay que revisar el flujo de trabajo para la aprobación de un modelo desde la aplicación. Podría ser mejor en cuanto a desempeño utilizar un servicio que verifique los modelos aprobados utilizando la base de datos NoSQL directamente.
