### ISSUE TITLE
Ver registros de especie de acuerdo a los privilegios de visualización

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#57]
Como administrador de BioModelos quiero que sea posible ver los registros de una especie de acuerdo con los privilegios de visualizacion que estos tengan

**Comment by valegrajales** [comment]
Criterio de aceptación: Los registros públicos son visibles por todos, los registros restringidos son visibles por los usuarios del grupo donde esta la especie y los privados no son visualizados por nadie.

**Comment by danflop** [comment]
@valegrajales @jivelasquezt @rbastidas Para poder desarrollar esta funcionalidad es necesario modificar o crear una nueva petición en la API que permita recibir un flag o key cuando se reconozca que una especie y un usuario pertenecen al mismo grupo.

**Comment by danflop** [comment]
Se crea un servicio temporal que retorna los registros con privilegios de visualización 0 (públicos) y 1 (sólo miembros de grupo) a los usuarios que hacen parte de un grupo. A futuro se considera que el API se conecte a la base de datos SQL para realizar esta verificación.

**Comment by danflop** [comment]
@erikasv Queda pendiente definir cómo se va a reemplazar el endpoint temporal para los registros con privilegios de visualización 1 (sólo miembros de grupo).
