### ISSUE TITLE
Poner Biomodelos 1 en nueva dirección

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#62]
Biomodelos 1 debe funcionar en la dirección: biomodelos_v1.humboldt.org.co

**Comment by valegrajales** [comment]
Criterio de aceptación: Al visitar biomodelos_v1.humboldt.org.co, la respuesta debe corresponder a la primera versión de Biomodelos

**Comment by danflop** [comment]
Se realiza solicitud a sistemas para creación del subdominio biomodelos_v1.humboldt.org.co apuntando a la IP de BioModelos v1.

**Comment by danflop** [comment]
La versión 1 de BioModelos ahora se encuentra en [biomodelosv1.humboldt.org.co](url)
