### ISSUE TITLE
Agregar licencia del modelo (default: by-nc.ci)

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#75]
En visor -> metadatos: Agregar licencia del modelo (default: by-nc.ci)

**Comment by valegrajales** [comment]
Lo hará Helena con apoyo de Ricardo de ser necesario

**Comment by rbastidas** [comment]
Se agrega el campo "license" a la coleccion "models" en pruebas y en Producción
db.getCollection('models').update({},{$set: {"license": null} },{ multi: true })
Se llena el mencionado campo con el valor por defecto: "by-nc-sa". En prueba y produccion
