### ISSUE TITLE
Indicar requerimiento de registro para descarga usando pop-up

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#76]
En visor -> Descarga modelo: Se genera un error cuando se trata de descargar sin estar registrado. Debe manejarse esta excepción (e.g. pop up)

**Comment by valegrajales** [comment]
Mostrar mensaje emergente que diga que no tiene permisos para descargar porque no se encuentra registrado

**Comment by danflop** [comment]
Cubierto por el issue #78
