### ISSUE TITLE
Ver opción "otros" en herramienta polígono al editar mapa en visor

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#86]
Como usuario de BioModelos quisiera ver en la herramienta de polígono la opción "Otros" y el espacio para hacer comentarios

**Comment by valegrajales** [comment]
Criterio de aceptación: La opción "otros"  y la sección de comentarios al editar los modelos con la herramienta polígono se se encuentran funcionales

**Comment by danflop** [comment]
Se agregó la opción "Otra" junto con un campo de texto que permitirá agregar un comentario a la edición. La opción marcada y el comentario quedarán almacenados como propiedades en el GeoJSON que se genera a partir del polígono.
