### ISSUE TITLE
Permitir el ingreso de nueva información asociada a un registro

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#87]
Como usuario de BioModelos quisiera que al añadir un registro se ingrese la información de número de catálogo, colección e institución

**Comment by valegrajales** [comment]
Criterio de aceptación: El formulario para agregar un nuevo registro incluye número de catálogo, colección e institución.

**Comment by erikasv** [comment]
Done.
