### ISSUE TITLE
Revisar acciones almacenadas al usar herramienta polígono

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#93]
Como desarrollador de BioModelos necesito revisar las acciones que se almacenan al usar la herramienta de polígono

**Comment by danflop** [comment]
Los valores que guardará el GeoJSON con los polígonos creados, será el mismo de los labels que puede ver el usuario: 

- Agregar área
- Sustraer área
- Recortar del polígono
- Otra

Los GeoJSON previamente almacenados en la base de datos relacional, ya se actualizaron con estos nuevos valores.
