### ISSUE TITLE
Construir archivo de internacionalización

### ISSUE THREAD

**Issue by valegrajales** [LBAB-Humboldt/BioModelos.v2#97]
Construir archivo para internacionalización de biomodelos en ingles y español. El archivo excel debe tener 3 columnas: Columna 1, etiqueta genérica (la etiqueta genérica no debe tener espacios, no debe usar caracteres especiales ni puntuaciones); Columna 2, texto correspondiente en español; Columna 3, texto equivalente en ingles. Usar codificación UTF8

Ejemplo
Etiqueta                  Español              Ingles
HomeHeader          Inicio                  Home
ModelsHeader        Modelos             Models

Este documento deberá cubrir aquellos contenidos que desean ser traducidos a otros idiomas (inicialmente ingles)

**Comment by valegrajales** [comment]
Criterio de aceptación: Archivo excel con la estructura solicitada listo para incorporarlo en frontend Biomodelos.

**Comment by rbastidas** [comment]
@jivelasquezt Traduccir tags de las secciones home y visor una vez esten disponibles en la versión de desarrollo de biomodelos.
